npx ng update @angular/cdk@14 @angular/cli@14 @angular/core@14 @angular/material@14 --force
npm info using npm@9.8.0
npm info using node@v20.5.0
npm info ok
npm info using npm@9.8.0
npm info using node@v20.5.0
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 14.2.12 to perform the update.
✔ Package successfully installed.
Using package manager: npm
Collecting installed dependencies...
Found 26 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^14.0.0", would install
"15.2.9")
                  Package "ng-packagr" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^14.0.0 || ^14.0.0-next || ^14.2.0-next", would install "15.2.9")
                  Package "@angular/animations" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
                  Package "@angular/common" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
                  Package "@angular/compiler" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
                  Package "@angular/animations" has an incompatible peer dependency to "@angular/core" (requires "15.2.9" (extended), would install "14.3.0").
                  Package "@angular/forms" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
                  Package "@angular/platform-browser" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
                  Package "@angular/platform-browser-dynamic" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
                  Package "@angular/router" has an incompatible peer dependency to "@angular/core" (requires "15.2.9", would install "14.3.0")
    Updating package.json with dependency @angular-devkit/build-angular @ "14.2.12" (was "13.1.4")...
    Updating package.json with dependency @angular/cli @ "14.2.12" (was "13.1.4")...
    Updating package.json with dependency @angular/compiler-cli @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency ng-packagr @ "14.2.2" (was "13.3.1")...
    Updating package.json with dependency typescript @ "4.8.4" (was "4.5.5")...
    Updating package.json with dependency @angular/animations @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency @angular/cdk @ "14.2.7" (was "13.1.3")...
    Updating package.json with dependency @angular/common @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency @angular/compiler @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency @angular/core @ "14.3.0" (was "13.1.3")...
    Updating package.json with dependency @angular/forms @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency @angular/material @ "14.2.7" (was "13.1.3")...
    Updating package.json with dependency @angular/platform-browser @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "15.2.9" (was "13.1.3")...
    Updating package.json with dependency @angular/router @ "15.2.9" (was "13.1.3")...
UPDATE package.json (1333 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

> Remove 'defaultProject' option from workspace configuration.
  The project to use will be determined from the current working directory.
UPDATE angular.json (4117 bytes)
  Migration completed.

> Remove 'showCircularDependencies' option from browser and server builders.
  Migration completed.

> Replace 'defaultCollection' option in workspace configuration with 'schematicCollections'.
  Migration completed.

> Update Angular packages 'dependencies' and 'devDependencies' version prefix to '^' instead of '~'.
UPDATE package.json (1333 bytes)
✔ Packages installed successfully.
  Migration completed.

> Remove 'package.json' files from library projects secondary entrypoints.
  Migration completed.

> Update TypeScript compilation target to 'ES2020'.
UPDATE tsconfig.json (987 bytes)
  Migration completed.

** Executing migrations of package '@angular/cdk' **

> Updates the Angular CDK to v14.

      ✓  Updated Angular CDK to version 14

  Migration completed.

** Executing migrations of package '@angular/core' **

> As of Angular version 13, `entryComponents` are no longer necessary.
  Migration completed.

> In Angular version 14, the `pathMatch` property of `Routes` was updated to be a strict union of the two valid options: `'full'|'prefix'`.
  `Routes` and `Route` variables need an explicit type so TypeScript does not infer the property as the looser `string`.
  Migration completed.

> As of Angular version 14, Forms model classes accept a type parameter, and existing usages must be opted out to preserve backwards-compatibility.
  Migration completed.

** Executing migrations of package '@angular/material' **

> Updates the Angular Material to v14.

      ✓  Updated Angular Material to version 14

  Migration completed.

Error: Repository is not clean. Please commit or stash any changes before updating.